name: hello_word
description: A new Flutter project.
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  path_provider: ^1.6.5
  hive: ^1.4.1+1
  firebase_auth: ^0.15.5+2
  firebase_core: ^0.4.4+2
  google_sign_in: ^4.1.4
  smooth_star_rating: ^1.0.4+2
  shared_preferences: ^0.5.6+2
  graphql_flutter: ^3.0.0
  cached_network_image: ^2.0.0
  shimmer: ^1.1.0
  validators: ^2.0.0+1
  dio: ^3.0.9
  flutter_mobx: ^1.0.1
  mobx: ^1.0.2
  flutter_modular: ^0.5.3
  flutter:
    sdk: flutter
dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.0.2
  build_runner: ^1.8.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nexa Script W00 Regular
      fonts:
        - asset: assets/fonts/nexa.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
scripts:
  mobxdel: flutter pub run build_runner build --delete-conflicting-outputs
  mobx: flutter pub run build_runner build